version: '2'
services:
    devweb-postgresql:
        image: postgres:9.6.5
        volumes:
            - "./postgresql/:/var/lib/postgresql/data/"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - 5432:5432
